---
version: "3.4"
services:
  web:
    image:
      "${DOCKER_REPOSITORY-hapi-fhir/}${DOCKER_IMAGE_NAME:-hapi-fhir-jpaserver-starter}:${DOCKER_IMAGE_TAG:-latest}"
    build: .
    ports:
      - target: 8080
        # change as needed (eg reverse proxy) in .env
        published: ${EXTERNAL_PORT:-8080}
    depends_on:
     - db

  db:
    image: postgres:${POSTGRES_VERSION:-12}
    ports:
      - target: 5432
    environment:
      POSTGRES_DB: hapifhir
      POSTGRES_USER: hapifhir
      POSTGRES_PASSWORD: hapifhir
    volumes:
      - source: postgres-data
        target: /var/lib/postgresql/data
        type: volume
volumes:
    postgres-data: {}
